import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// Vite configuration for the React frontend.
// Original scaffold generated by Vite.
// Additional server settings added for Docker container networking.

export default defineConfig({
  plugins: [react()],

  server: {
    // Allow the Vite dev server to listen on all container interfaces.
    // Without this, nginx and other Docker containers cannot reach Vite.
    host: '0.0.0.0',

    // Explicitly run Vite on port 5173.
    // nginx will proxy frontend traffic to this port.
    port: 5173,

    allowedHosts: ['react', 'localhost']
  }
})