server {

    listen 80;

    # If the URL starts with /api/ send it to djang0:8000
    location /api/ {
        
        # Forward the request to the django container on the internal docker network
        proxy_pass http://django:8000;
        
        # Tell django what the original hostname was
        proxy_set_header Host $host;
        
        # Tell Django the real IP address of the browser
        # Without this Django only sees Nginx's IP, not the actual client
        proxy_set_header X-Real-IP $remote_addr;
    }

    # If the URL starts with /admin/ send it to djang0:8000
    location /admin/ {
        
        # Forward the request to the django container on the internal docker network
        proxy_pass http://django:8000;
        
        # Tell django what the original hostname was
        proxy_set_header Host $host;
        
        # Tell Django the real IP address of the browser
        # Without this Django only sees Nginx's IP, not the actual client
        proxy_set_header X-Real-IP $remote_addr;
    }

    # If the URL starts with /static/ send it to djang0:8000
    location /static/ {
        
        # Forward the request to the django container on the internal docker network
        proxy_pass http://django:8000;
        
        # Tell django what the original hostname was
        proxy_set_header Host $host;
        
        # Tell Django the real IP address of the browser
        # Without this Django only sees Nginx's IP, not the actual client
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Everything that did not match /api/ (all React frontend requests (HTML, CSS, JS, images))
    location / {

        # Forward the request to the React container on the internal Docker network
        proxy_pass http://react:3000;

        # Same as above — pass original hostname to React
        proxy_set_header Host $host;

        # Same as above — pass real client IP to React
        proxy_set_header X-Real-IP $remote_addr;
    }
}
