# Generated by Django 5.1.2 on 2026-05-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_handler', '0002_device_motionevent_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='battery',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='connection_interrupted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='signal_strength',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motionevent',
            name='battery_at_event',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motionevent',
            name='event_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='motionevent',
            name='event_type',
            field=models.CharField(default='motion', max_length=100),
        ),
        migrations.AddField(
            model_name='motionevent',
            name='motion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='motionevent',
            name='sensor_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motionevent',
            name='signal_strength_at_event',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motionevent',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
