#!/usr/bin/env python
"""
manage.py — Django's Command Line Toolbelt
------------------------------------------
This file is auto-generated by Django and is your main way of interacting
with the project from the terminal during development.

What it does:
  Provides a set of commands to manage the Django project such as:
    python manage.py runserver      — starts the development server
    python manage.py migrate        — applies database changes
    python manage.py makemigrations — generates new migration files from model changes
    python manage.py createsuperuser — creates an admin user

What it works with:
  - basestation_config/settings.py — points to this as the settings module
  - All Django management commands built into the framework
  - Your venv — Django must be installed and venv must be active to use this

Note: This file is not used in production inside Docker.
Docker runs migrations and starts the server via the CMD in the Dockerfile.
"""
import os
import sys


def main():
    """Run administrative tasks."""
    # Tell Django where to find the project settings
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'basestation_config.settings')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()